# Generated by Django 3.0.8 on 2021-04-10 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0006_maxplayed_recommended_songs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recommended_songs',
        ),
    ]
